### ISSUE TITLE
Wheezy: "ps: command not found"

### ISSUE THREAD

**Issue by ivanbrykov** [tianon/docker-brew-debian#13]
Hi, I am getting the following error: "ps: command not found" while trying to install anything on the image. E.g. RVM fails to run complaining:

```
/etc/profile.d/rvm.sh: line 9: ps: command not found
/etc/profile.d/rvm.sh: line 10: ps: command not found
/usr/local/rvm/scripts/rvm: line 15: ps: command not found
```

I tried to find 'ps' manually but was unable to do so. 

Any suggestions?

**Comment by ain** [comment]
:+1: for the `procps` suggestion. Works.

**Comment by kskalvar** [comment]
+1

**Comment by izerui** [comment]
centos：
yum install -y procps
