### ISSUE TITLE
/usr/share/doc uses 7MB

### ISSUE THREAD

**Issue by SvenDowideit** [tianon/docker-brew-debian#18]
that's about 15% of the size of debian:latest

https://www.debian.org/doc/debian-policy/ch-docs.html suggests to me that we could get `debian:latest` to 77MB...

**Comment by SvenDowideit** [comment]
mmm, `/usr/share/man` is 5GB, even though man is not there - 

I'm kinda wondering if we can have `debian:mini-latest` which removes it, and then `debian:latest` would add it back

feel free to say 'no' ;)

**Comment by tianon** [comment]
This one makes me wary because there's not just a simple `apt-get install` that can be performed to bring those files back.  We'd basically have to force APT to reinstall all the base packages to get them back (or maintain two images, as you postulate here).

**Comment by SvenDowideit** [comment]
agreed - I ended up deleting docs, locale and zoneinfo for my `slim container` talk at lca - but mostly as an example of what you should do when curating your own base images - with the strong caveat that you should make the effort to know what's in your base images.

and in that light, I agree that the Docker official images need to be more generic.

**Comment by accursoft** [comment]
I've implemented this in [accursoft/micro-jessie](https://registry.hub.docker.com/u/accursoft/micro-jessie/).
