### ISSUE TITLE
Policy for security updates

### ISSUE THREAD

**Issue by kuba** [tianon/docker-brew-debian#22]
Over the past few days there have been 3 security updates to Debian that affect base and buildpack-deps images:
- #21
- https://github.com/docker-library/buildpack-deps/issues/23
- https://github.com/docker-library/buildpack-deps/issues/24

Please let me know if GitHub is not the right place to report those issues and if so, sorry for the spam!

Is there a tool that monitors Debian security mailing list and checks for the vulnerabilities in the images?  It would be quite easy to hack it for base images, where build logs (with package versions) are stored in the repo; not so easy for buildpack-deps (would it be possible to store `apt-get install` or `dpkg -l` logs?)...

In general, what is the typical security policy for Docker images updates? Should `apt-get upgrade` be run for derivative image builds and/or "leaf" containers?

Thanks!

**Comment by tianon** [comment]
GitHub's definitely a great place to report these.  The Debian base image
was actually completely rebuilt yesterday, and the buildpack-deps image was
rebuilt early this morning.

The Debian Security Tracker (https://security-tracker.debian.org/tracker/)
has a database that can be downloaded (debsescan uses it), and I think it
would be really awesome if we could work up a tool that actually scans
images for known vulnerable package versions (essentially debsescan but for
Docker images).  It could even go the extra mile to tell us whether the fix
is even available yet in the appropriate APT repos.

**Comment by tianon** [comment]
"dpkg-query --show" gives us the versions of the packages that are
installed, and "dpkg --compare-versions" can be used to compare
against known-fixed or known-vulnerable versions, so this really isn't
an insurmountable problem to solve! :smile:

**Comment by tianon** [comment]
Given that tools like [Clair](https://github.com/coreos/clair) and [Docker's own Nautilus](http://www.eweek.com/security/docker-doubles-down-on-security-with-nautilus-hardware-encryption.html) either already are or will be GA soon, I think we can safely close this.  We've also revamped our CVE process at the official-images level to track these somewhat more aggressively (https://github.com/docker-library/official-images/issues?q=label%3Acve-tracker).
