### ISSUE TITLE
Add resolvconf in the rootfs archive

### ISSUE THREAD

**Issue by christopherobin** [tianon/docker-brew-debian#23]
The `resolvconf` package is depended upon by several packages and cannot be installed by any other mean than the rootfs archive that is added at the beginning. This is because it tries to remove `resolv.conf` at install time and docker forbids this sorts of modification to the file.

It would really help if it was included. I can do a PR if necessary.

**Comment by tianon** [comment]
Oh man, this is a nasty one that slipped through the cracks in my email until just now. :disappointed:

I think the workarounds provided in https://github.com/docker/docker/issues/1297#issuecomment-115360187 are probably worth documenting.  I don't think I've run into a package yet with a _hard_ dependency on `resolvconf`, but I'd love some prominent examples so we can update the docs to mention some of them explicitly.

For the sake of completeness, the workarounds provided there are to do one of the following:
```Dockerfile
RUN mkdir -p /var/lib/resolvconf && touch /var/lib/resolvconf/linkified
```
Or:
```Dockerfile
RUN echo 'resolvconf resolvconf/linkify-resolvconf boolean false' | debconf-set-selections
```

(Both of which should be essentially equivalent, but with the latter probably being more well-supported in the face of future `resolvconf` versions.)

**Comment by tianon** [comment]
This repository is now deprecated in favor of https://github.com/debuerreotype/docker-debian-artifacts, which builds reproducible Debian rootfs tarballs using https://github.com/debuerreotype/debuerreotype. :+1:
