### ISSUE TITLE
Debian 7.9

### ISSUE THREAD

**Issue by nervo** [tianon/docker-brew-debian#28]
Any chance to have official debian images for the so-fresh debian 7.9 ?

**Comment by tianon** [comment]
Yep! Building new tarballs right now.

**Comment by nervo** [comment]
Dude, you're awesome :)

**Comment by tianon** [comment]
Tarballs are built, https://github.com/docker-library/official-images/pull/1032 is the place to watch for the updates to go out. :+1:

**Comment by nervo** [comment]
Ah ! Good to know, thanks

**Comment by msimerson** [comment]
This can be closed right, since 7.9 is merged upstream?

**Comment by tianon** [comment]
Indeed, thanks! :+1:
