### ISSUE TITLE
Weird thing about ports

### ISSUE THREAD

**Issue by beetree** [tianon/docker-brew-debian#30]
I feel like an idiot for opening such a basic issue, but there's something that is different with this image that I don't fully understand.

If I do this (for ubuntu):
```
host> docker run -it -p 8080:8080 ubuntu
container> apt-get update
container> apt-get -y install netcat
container> netcat -l 8080
host> echo hey | netcat localhost 8080
```
Then the container prints "hey" as excepted.

Now I do the same but for the debian image (after having stopped the container above):
```
root@m3209:~# docker run -it -p 8080:8080 debian
root@f7d3f71aced2:/# apt-get update
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Ign http://httpredir.debian.org jessie InRelease
Get:2 http://security.debian.org jessie/updates/main amd64 Packages [182 kB]
Get:3 http://httpredir.debian.org jessie-updates InRelease [128 kB]
Get:4 http://httpredir.debian.org jessie Release.gpg [2373 B]
Get:5 http://httpredir.debian.org jessie Release [148 kB]
Get:6 http://httpredir.debian.org jessie-updates/main amd64 Packages [3614 B]
Get:7 http://httpredir.debian.org jessie/main amd64 Packages [9035 kB]
Fetched 9563 kB in 2s (3207 kB/s)
Reading package lists... Done
root@f7d3f71aced2:/# apt-get -y install netcat
Reading package lists... Done
Building dependency tree... Done
The following extra packages will be installed:
  netcat-traditional
The following NEW packages will be installed:
  netcat netcat-traditional
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 75.3 kB of archives.
After this operation, 194 kB of additional disk space will be used.
Get:1 http://httpredir.debian.org/debian/ jessie/main netcat-traditional amd64 1.10-41 [66.3 kB]
Get:2 http://httpredir.debian.org/debian/ jessie/main netcat all 1.10-41 [8962 B]
Fetched 75.3 kB in 0s (221 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package netcat-traditional.
(Reading database ... 7528 files and directories currently installed.)
Preparing to unpack .../netcat-traditional_1.10-41_amd64.deb ...
Unpacking netcat-traditional (1.10-41) ...
Selecting previously unselected package netcat.
Preparing to unpack .../netcat_1.10-41_all.deb ...
Unpacking netcat (1.10-41) ...
Setting up netcat-traditional (1.10-41) ...
update-alternatives: using /bin/nc.traditional to provide /bin/nc (nc) in auto mode
Setting up netcat (1.10-41) ...
root@f7d3f71aced2:/# netcat -l 8080
```

And when I do `echo hey | netcat localhost 8080` nothing is posted inside the container.

Do I need to do something in this image to open up ports?

Sorry for opening up an issue about such a trivial problem but I can't figure out what is wrong, and I've tried to recreate the issue I'm having in an as clean reproducible way as possible to ensure it is easy for you to help me out.

Some other info about the host:
```
docker info
Containers: 128
Images: 278
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 534
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-28-generic
Operating System: Ubuntu 15.04
CPUs: 24
Total Memory: 125.8 GiB
Name: m3209.contabo.host
ID: LGC5:GMUP:3KJM:VDX6:44KD:O3TV:LOAR:WUPO:5PUZ:JQCX:K6E4:Q75Q
WARNING: No swap limit support

uname -r
3.19.0-28-generic
```

Thanks for the help!

EDIT:
If I do `docker run -it -p 8080:8080 debian apt-get update && apt-get -y install netcat && netcat -l 8080` then everything works properly. It seems that opening up the console and then listening to the ports is what causes the problem.

**Comment by tianon** [comment]
When you do `docker run -it -p 8080:8080 debian apt-get update && apt-get -y install netcat && netcat -l 8080`, it actually runs netcat on your host, not inside the container.  What you meant was probably more something `docker run -it -p 8080:8080 debian sh -c 'apt-get update && apt-get -y install netcat && netcat -l 8080'`.

I wonder if the `netcat` on Debian is different from the `netcat` in Ubuntu?

**Comment by yosifkit** [comment]
Looks like you are missing the port specifier `-p`, so it would be `netcat -l -p 8080`.

**Comment by beetree** [comment]
Oh, I see. So netcat is different on Debian.

Thanks for helping! I really appreciate it!

**Comment by md5** [comment]
Debian and Ubuntu both have "netcat-openbsd" and "netcat-traditional". In
both cases, the packages themselves are virtually the same. I only see one
patch in Ubuntu's "netcat-openbsd", though I'm not sure it's applied in
14.04: https://patches.ubuntu.com/n/netcat-openbsd/​

Also, it looks like both Debian and Ubuntu install "netcat-traditional" by
default.

**Comment by tianon** [comment]
Although Ubuntu has "netcat-openbsd" installed in the base set.

**Comment by md5** [comment]
Well that's confusing... They install "netcat-openbsd" without installing
"netcat"?​ Seems like an odd choice.

**Comment by tianon** [comment]
![](http://vignette3.wikia.nocookie.net/glee/images/e/e2/Office-karen-shrug.gif/revision/latest?cb=20150106110113)

**Comment by md5** [comment]
Looks like `netcat` depends on `netcat-traditional` as opposed to having it as a "recommends", so I guess it makes sense.
