### ISSUE TITLE
Starting Debian services when Debian docker container is launched

### ISSUE THREAD

**Issue by mountaindude** [tianon/docker-brew-debian#33]
This might be really obvious... still cannot figure it out. 
I am using a Debian Docker container to host Apache, sshd and a couple of other daemons. Works great, except that none of the daemons start when the container is launched. I have to start them manually, which is possible, but a pain. 
I am missing something obvious?

Running Docker on a Synology NAS, using latest OS (DSM 5.2-5644 Update 2), running Docker 1.6.2 (which is the latest version available on Synology, as of right now).

Thx.

**Comment by jhonatanpiffer** [comment]
You can use a docker file to do this:
https://www.digitalocean.com/community/tutorials/docker-explained-using-dockerfiles-to-automate-building-of-images

You can use [RUN] command to start your daemons

**Comment by tianon** [comment]
So, the reason daemons don't start up is that the container doesn't launch `/sbin/init`, which is normally responsible for launching services.  What I would recommend is splitting each service into a separate container, or looking into a tool such as `supervisor` or `runit` to manage multiple daemon processes.

**Comment by damirv** [comment]
We're using [s6-overlay](https://github.com/just-containers/s6-overlay) for this purpose and it works quite well for us.
