### ISSUE TITLE
`libusb1` is not included in Jessie Docker image

### ISSUE THREAD

**Issue by SimplicityGuy** [tianon/docker-brew-debian#34]
Why is `libusb1` not included in the Debian Jessie Docker image? My laptop has Jessie installed locally:
```
lrwxrwxrwx  1 root root      19 Oct 21  2014 libusb-0.1.so.4 -> libusb-0.1.so.4.4.4
-rw-r--r--  1 root root   30904 Oct 21  2014 libusb-0.1.so.4.4.4
lrwxrwxrwx  1 root root      19 Jun 16  2014 libusb-1.0.so.0 -> libusb-1.0.so.0.1.0
-rw-r--r--  1 root root   97208 Jun 16  2014 libusb-1.0.so.0.1.0
```

However, in the Jessie container running on the same machine:
```
lrwxrwxrwx 1 root root      19 Oct 21  2014 libusb-0.1.so.4 -> libusb-0.1.so.4.4.4
-rw-r--r-- 1 root root   30904 Oct 21  2014 libusb-0.1.so.4.4.4
```

Seems like `libusb1` should be included.

**Comment by tianon** [comment]
It looks like nothing in the base requires `libusb-1.0`, so it hasn't been pulled in.  Checking https://packages.debian.org/file:libusb-1.0.so.0 shows that it's provided by `libusb-1.0-0`, so installing that should bring it in.

**Comment by SimplicityGuy** [comment]
Ah! Indeed! `apt-get install libusb-1.0-0` addresses this. Thanks for pointing that out.
