### ISSUE TITLE
Publish an 8.2 version?

### ISSUE THREAD

**Issue by mkobit** [tianon/docker-brew-debian#36]
I went through a of images on [Docker Hub](https://hub.docker.com/_/debian/), but I didn't see any of them with an **8.2** version. I looked at a few of them like this, but was unable to find what I was looking for.

```
cat /etc/debian_version
```

I am in a situation where I am currently restricted to using it. Would you be able to publish that version as well?

**Comment by yosifkit** [comment]
It is not in the description under "Supported Versions", but it is over on the [tags page](https://hub.docker.com/r/library/debian/tags/ and so it is there for pulling.
```console
$ docker pull debian:8.2
8.2: Pulling from library/debian
523ef1d23f22: Pull complete 
140f9bdfeb97: Pull complete 
Digest: sha256:3aa657c392fa424c0325eccb9d961d34a2a2e8f95463068441e87c7e6f03f7ee
Status: Downloaded newer image for debian:8.2
$ docker run -it --rm debian:8.2 cat /etc/debian_version
8.2
```

**Comment by mkobit** [comment]
Ahh, thanks. I stupidly did not even look at that page.
