### ISSUE TITLE
httpredir.debian.org

### ISSUE THREAD

**Issue by tianon** [tianon/docker-brew-debian#37]
The service appears to be somewhat poorly-maintained at this point.  https://github.com/docker/docker/issues/21512 is the most recent report I've seen of problems that are messier than the normal `Hash Sum mismatch` issues we usually run into, and it's not the first I've seen either.

http://deb.debian.org/ looks really promising (and is still hosted on a `debian.org` subdomain, so is "supported" by DSA/Debian System Administration).  The main issues there are that it is only supported for `stretch` (current `testing`) and above, and `debootstrap` doesn't support it (yet?), so we'd likely have to just hard-code `http://cdn-fastly.deb.debian.org/debian` anyhow, and I don't know what the support level of doing that is going to be now or in the future.

Any further thoughts, @paultag?

**Comment by tianon** [comment]
The discussion (or lack) in both https://github.com/rgeissert/http-redirector/issues/55 and https://github.com/rgeissert/http-redirector/issues/72 is also of note/interest here.

**Comment by tianon** [comment]
I think it's also worth noting the following from the main description of the service:
> If you are having issues with the redirector itself, please email me instead. Hash sum mismatches, poor mirror selection, etc., I'd like to know about all that.

(but I haven't been able to reproduce issues with the service, so I don't feel comfortable reporting them myself without being able to adequately describe what's being seen and potentially help debug)

**Comment by tianon** [comment]
More color from Raphael himself (this exact topic is currently under discussion on the `debian-project` mailing list): https://lists.debian.org/debian-project/2016/04/msg00018.html

**Comment by ijc25** [comment]
FYI I asked about recommended mirror service in a thread on debian-devel today and got [a response](https://lists.debian.org/debian-devel/2016/10/msg00362.html) from a Debian System Admin (although not, I don't think, speaking formally with that hat on), TL;DR It seems that deb.debian.org is now considered a suitable alternative to httpredir.

Note that http://deb.debian.org/ does support Jessie and earlier too, at least according to its front page.

**Comment by tianon** [comment]
@ijc25 very interesting indeed!  I think the standard HTTP redirect is somewhat new -- last time I tried using `deb.debian.org` it didn't include that, and so using `debootstrap` directly against it didn't work either :+1:

Given that it's still noted as experimental, I'm hesitant to update jessie to use it right away, although I think updating stretch/sid is a no-brainer (with the goal that if it proves stable there, updating jessie can/should come shortly following).  Does that sound like a fair plan?

**Comment by ijc25** [comment]
@tianon IMHO that sounds like a most excellent plan!

**Comment by tianon** [comment]
@ijc25 :heart:!  Updated in 33e87c3 -- I'll leave this open as a reminder that if all goes well, we should switch jessie over too. :+1:

**Comment by ijc25** [comment]
FYI the words about it being experimental have just been removed from `deb.debian.org`!

**Comment by tianon** [comment]
@ijc25 that's awesome, and I imagine https://anonscm.debian.org/cgit/d-i/debootstrap.git/commit/?id=9e8bc60ad1ccf3a25ce7890526b70059f3e770de was probably a related part of the discussion that led to it (or from it) :smile: :+1:

I think that's as official as we could possibly get -- I'm going to switch stable over now.  All my own testing has been really positive! :metal:
