### ISSUE TITLE
squeeze image

### ISSUE THREAD

**Issue by mcanevet** [tianon/docker-brew-debian#38]
Could you please push an official squeeze image on github with sources.list pointing to archive.debian.org?

**Comment by tianon** [comment]
I worked with @paultag on this and together we put together https://hub.docker.com/r/debian/eol/ which contains every release from squeeze back to potato (which was the first release to _fully_ use APT, and thus the earliest release `debootstrap` can create us a simple chroot for). :+1:

(Now I think it'd probably be prudent for us to add a link to that repo over on the README for the `debian` image. :smile:)

**Comment by tianon** [comment]
https://github.com/docker-library/docs/pull/535 :+1:
