### ISSUE TITLE
Can no longer build images from debian:jessie

### ISSUE THREAD

**Issue by asciifaceman** [tianon/docker-brew-debian#39]
#### Use debian jessie
FROM debian:jessie

```
Build failed: Get https://registry-1.docker.io/v2/library/debian/manifests/jessie: unauthorized: incorrect username or password
```

Any other information you would need? This has completely halted our build pipeline

**Comment by tianon** [comment]
Sorry for the delay!  The only things I know of that could cause an issue like this are either an issue with the Docker Hub (which would be worth emailing support@docker.com about), or a firewall which is getting a little over-aggressive with your traffic. :disappointed:

**Comment by tianon** [comment]
In either case, there's not much I can do for you here, since this isn't really an issue with this image, perse. :cry:

Closing, but feel free to continue to comment here!
