### ISSUE TITLE
can't uncompress tar.xz files in debian:jessie image

### ISSUE THREAD

**Issue by chrpinedo** [tianon/docker-brew-debian#40]
I can't uncompress tar.xz files in your debian jessie image.

```bash
root@cf8b1803ada8:/# tar -xJf node-v4.4.3-linux-x64.tar.xz 
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
root@cf8b1803ada8:/# curl -L https://nodejs.org/dist/v4.4.3/node-v4.4.3-linux-x64.tar.xz | tar -xJ
tar (grandchild): xz: Cannot exec: No such file or directory
tar (grandchild): Error is not recoverable: exiting now
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8070k  100 8070k    0     0  1688k      0  0:00:04  0:00:04 --:--:-- 1989k
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Comment by tianon** [comment]
That's because the `xz` utility is not included in the default `minbase` set of packages for Debian; can you try again after installing the [`xz-utils` package](https://packages.debian.org/jessie/xz-utils)?

**Comment by chrpinedo** [comment]
You are right, sorry for disturbing you with such a simple issue. Thanks!

**Comment by tianon** [comment]
No problem, glad you got it solved. :+1:

**Comment by tweaty100** [comment]
@tianon @chrpinhanedo 
can you please explain this as i don't understand what changes you did here? sorry i am new to linux but please explain this as i am also facing same error?

**Comment by tianon** [comment]
You need to install the "xz-utils" package.
