### ISSUE TITLE
debian jessie svn checkout error

### ISSUE THREAD

**Issue by junneyang** [tianon/docker-brew-debian#41]
1. cat /etc/issue
Debian GNU/Linux 8 \n \l

2. uname -a
Linux 8f1e3e13aa3c 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 GNU/Linux

3. svn --version
svn, version 1.9.4 (r1740329)

4. echo "t" | svn checkout --no-auth-cache --quiet --username ${SVN_USERNAME} --password ${SVN_PASSWORD} -r ${SQL_REPO_VERSION} ${SQL_DIR} ${DST_REPO_PATH}
svn: E170013: Unable to connect to a repository at URL 'https://192.168.5.246/svn/cloud/Omais/trunk/storage'
svn: E230001: Server SSL certificate verification failed: certificate issued for a different hostname, issuer is not trusted

5. screenshots below:
![qq 20160511093118](https://cloud.githubusercontent.com/assets/6802322/15167395/26bee9ae-175b-11e6-936e-a705e43f5706.png)

but if i use ubuntu docker image, the same svn operation works.

i google many solutions for this error, but not works.
i dont know if it's wrong with the jessie or the svn.

thanks!

**Comment by yosifkit** [comment]
I think this may be another victim of https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812708.
