### ISSUE TITLE
provide a jessie-proposed-updates image

### ISSUE THREAD

**Issue by jon-d** [tianon/docker-brew-debian#42]
Hi,

Some packages are reaching stable through the "proposed-updates" mechanism. It can take a few month to get the packages out of this repository and I think it would be interesting to provide a Debian docker image with this repository enabled by default.

Thanks a lot for considering this idea.

**Comment by tianon** [comment]
Sorry for not seeing this sooner!  I'd recommend doing something similar to the `Dockerfile` for the `jessie-backports` image and instead simply adding the appropriate line in a file in `/etc/apt/sources.list.d/` directly. :sweat_smile: :+1:
