### ISSUE TITLE
 Accented characters problem in container

### ISSUE THREAD

**Issue by galaad** [tianon/docker-brew-debian#44]
Problem description [here](https://linuxfr.org/forums/linux-debian-ubuntu/posts/comment-passer-les-caracteres-accentues-a-un-shell-bash-dans-docker)

Problem doesn't appear on docker ubuntu:xenial

Solution on ubuntu : http://jaredmarkell.com/docker-and-locales/

**Comment by tianon** [comment]
This sounds like a duplicate of #45 -- mind trying the solution linked there?

**Comment by tianon** [comment]
This repository is now deprecated in favor of https://github.com/debuerreotype/docker-debian-artifacts, which builds reproducible Debian rootfs tarballs using https://github.com/debuerreotype/debuerreotype. :+1:
