### ISSUE TITLE
LC_ALL: cannot change locale (en_US.UTF-8)

### ISSUE THREAD

**Issue by junneyang** [tianon/docker-brew-debian#45]
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL en_US.UTF-8

error info:
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

**Comment by junneyang** [comment]
solved already, ref:
https://www.thomas-krenn.com/en/wiki/Perl_warning_Setting_locale_failed_in_Debian
notice:
dpkg-reconfigure locales should execute nointeractive

**Comment by timthelion** [comment]
Can you please re-open this bug and fix the image? The instructions in the link don't work for me. Is there a strong case for non-standard configuration of the official image? Debian is UTF8 by default when installed normally.

**Comment by nedyang** [comment]
it is not working for me as well.

**Comment by tianon** [comment]
The image includes Debian's default locales for a standard "minbase" install, which is the absolute bare minimum footprint which can still be called "Debian", and thus only includes `C` and `C.UTF-8`.  A desktop install of Debian usually includes locales, but a bare install does not, and usually defaults to either `C` or `POSIX`.  I've found that for most applications, `C.UTF-8` is sufficient when a UTF-8 locale is required.  The Python official image is an excellent example of this: https://github.com/docker-library/python/blob/edde349541e11f66dcc79cde1674317d065ddbdd/3.6/Dockerfile#L8

**Comment by tianon** [comment]
I've opened https://github.com/docker-library/docs/pull/703 to hopefully help clarify this point in the image documentation.

**Comment by raphaunix** [comment]
This worked for me:

```
echo "LC_ALL=en_US.UTF-8" >> /etc/environment
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
locale-gen en_US.UTF-8
```
Enjoy.

**Comment by lpcpp** [comment]
just run this cmd in your teminal:    sudo apt-get install locales

**Comment by a2f0** [comment]
@raphaunix you're a lifesaver.
