### ISSUE TITLE
Image can't be pulled via 8.5 tag

### ISSUE THREAD

**Issue by genebarker** [tianon/docker-brew-debian#47]
The latest release can not be pulled using the 8.5 tag.

```
$ docker pull debian:8.5
Pulling repository debian
Tag 8.5 not found in repository debian
```

**Comment by paddy-hack** [comment]
Ditto for 7.11.

**Comment by tianon** [comment]
There was an issue with the official build server which caused a slight lag; tags should be available now.

**Comment by paddy-hack** [comment]
Thanks for the clarification.  The 8.5 and 7.11 tags pull just fine but they don't match the hashes for the [8.5 tags](https://github.com/docker-library/docs/blob/414861529d99b4ff17b3a4d5e7bd0ecf39687380/debian/tag-details.md#debian85) and [7.11 tags](https://github.com/docker-library/docs/blob/414861529d99b4ff17b3a4d5e7bd0ecf39687380/debian/tag-details.md#debian711).

The tags I just pulled (around 2016-06-10 21:30 JST) are
```
debian@sha256:8b1fc3a7a55c42e3445155b2f8f40c55de5f8bc8012992b26b570530c4bded9e
debian@sha256:bd768708961266e250feb775923cdb5bc6b270e696063d955e661d137cdf32e8
```
for 8.5 and 7.11 respectively.

Now either I don't understand what all these SHA256 hashes are about and the sense of security they are supposed to provide or something is seriously skewed/screwed :disappointed:
I even went so far as to clone docker-library/docs and search the `git log -p` output for `debian` for any mention of the first 7,8 digits of the `sha256` checksums of the images I pulled.  No matches whatsoever.

I'd really like to understand what's going on here.  Care to explain :question:

**Comment by tianon** [comment]
The digests aren't exactly for security, but more for consistency.  If you pull-by-digest, you can be assured that you'll receive the same bits every time, regardless of updates to the image in the interim, or even moving the entire process to a new cluster across the globe.

The `tag-details.md` files are updated via a periodic Jenkins job, and it _appears_ that https://github.com/docker-library/docs/commit/414861529d99b4ff17b3a4d5e7bd0ecf39687380#diff-95d130252cde63b922d301880543c091 is the commit in question which added `debian:8.5`'s digest (`debian@sha256:e36a90f08bdede2b53d77350e695448012c6830f70dfb09f99dba7839d685172`), but it does indeed appear that the digest for that is wrong (`Error response from daemon: manifest unknown: manifest unknown` while pulling that digest, and `sha256:8b1fc3a7a55c42e3445155b2f8f40c55de5f8bc8012992b26b570530c4bded9e` is the digest I actually get when I pull, same as you noted), so I need to do some investigating in that script into why it's pulling the wrong digest value now. :cry:

**Comment by genebarker** [comment]
Just confirming that the pull for `debian:8.5` works. Thanks for jumping on
this so quickly. Kind of weird about the different hashes, but I can live
with it. Thanks again, Eugene.

**Comment by paddy-hack** [comment]
@tianon Thanks for the info and looking into this.

**Comment by genebarker** [comment]
Hi Olaf, haven't looked at this since my last email... however, this
morning, I typed `docker images` and noticed that image ID's now match.
Congrat's and thanks again! Eugene.

**Comment by genebarker** [comment]
Oops. Thank you both. Eugene.
