### ISSUE TITLE
create "slim" variants without bits like /usr/share/locale and /usr/share/doc

### ISSUE THREAD

**Issue by tianon** [tianon/docker-brew-debian#48]
I'd thought about removing things like docs and locales from these images multiple times (and every time, re-resolved that it was inappropriate to do so), but I hadn't thought about making separate _variants_ with those disabled until @aburch suggested it, so I'm filing this issue to help me remember to look into doing so. :smile:

**Comment by md5** [comment]
Wouldn't this result in the license files not being included and potentially running afoul of licensing restrictions?

**Comment by tianon** [comment]
Oh, interesting point -- wonder what @paultag's thoughts on that are.

It'd be trivial to point to where the licensing information is on the Hub description (which we already do IIRC), but I don't know if we'd need to ensure that `/usr/share/doc/*/copyright*` sticks around for sure (and I don't know whether `dpkg`'s exclusions support exceptions like that, which is worth looking into as well).

**Comment by aburch** [comment]
@md5 Keeping `/usr/share/doc/*/copyright` around should be enough in theory. (A few packages ship the actual license in an extra file contrary to what Policy requires, but at least copyright should mention the license name.)

`dpkg` supports such exclusions with exceptions, see man:dpkg(1) on `--path-exclude` and `--path-include`. It even has `copyright` as the example of choice. debootstrap has no exclusion mechanism as far as I know.

So the implementation needs some initial removal plus adding the `--path-exclude`/`--path-include` options to some file in `/etc/dpkg/dpkg.cgf.d` for packages installed later.

**Comment by tianon** [comment]
Indeed, that sounds really sane, and mirrors what's mentioned in https://wiki.ubuntu.com/ReducingDiskFootprint#Drop_unnecessary_files (which is one example I'd been reading when considering this previously). :+1:

**Comment by paultag** [comment]
So, users removing their licenses is actually fine, so long as you don't distribute them to another person without the license. So, I'm mildly sketch on removing all copyright information, but I like the idea of a slim version, trimming stuff up. =

Keeping copyright sounds sufficient for allowing redistribution :+1:

**Comment by tianon** [comment]
Ok, playing with the example from Ubuntu's wiki there, I've got `debian:sid` from ~99.81 MB down to ~88.75 MB (with just the "Documentation" section).

There's another ~33 MB that's ripe within `/usr/share/locale`, although I'm less sure about how much of that we can reasonably cull before we start breaking things.  Would we be OK to cull the entire directory, or do we need to keep some minimal set such as `/usr/share/locale/en*`?

**Comment by tianon** [comment]
(thanks @paultag :heart:)

**Comment by tianon** [comment]
Another place we can look to shave a few bits is `/usr/share/zoneinfo`.

**Comment by md5** [comment]
@tianon Removing parts of either `/usr/share/locale` or `/usr/share/zoneinfo` seems error-inducing. In the event that users needed to restore some of the removed content, how would they do that? `apt-get --reinstall install`?

**Comment by md5** [comment]
In the case of `/usr/share/doc` or `/usr/share/man`, there shouldn't be any operational need to restore those files inside a container.

**Comment by tianon** [comment]
They'd need to modify/remove our `dpkg.d` configuration bits, and then yes, `--reinstall` on the packages which own the removed files should do the trick to restore them.

**Comment by tianon** [comment]
(So that's a really strong argument for keeping those bits explicitly defined in individual `dpkg.d` files such that they're trivial to remove.)

**Comment by tianon** [comment]
In theory, we might also be able to use `dpkg` itself to include in the "exclude" files the list of packages which need to be reinstalled (at least from the minbase set) in order to restore the removed files.

**Comment by andsens** [comment]
Heh, you should subscribe to the debian-cloud mailing list. I posted a message there about this exact issue: https://lists.debian.org/debian-cloud/2016/06/msg00002.html
I created [bootstrap-vz](https://github.com/andsens/bootstrap-vz), which can bootstrap debian for a lot of different environments, including docker.

You should take a look at the [minimize_size](https://github.com/andsens/bootstrap-vz/tree/96086329e629f6edb83e24cee79e265e029a7f55/bootstrapvz/plugins/minimize_size) plugin. I do some [crazy stuff](https://github.com/andsens/bootstrap-vz/blob/96086329e629f6edb83e24cee79e265e029a7f55/bootstrapvz/plugins/minimize_size/assets/bootstrap-script.sh) to reduce the size significantly by excluding locales, manpages etc. right from the get-go when running debootstrap. The trick is to create your "own" bootstrap script (the \[SCRIPT\] part in the `debootstrap` command), which just wraps the normal distribution script.

I'd love to explain it further if you're interested.

**Comment by ehlers** [comment]
Just tested jessie-slim and it's working great, good job.

I had only difficulties with the (non-free) snmp-mibs-downloader package. It contains documents with mibs in /usr/share/doc/mibiana and /usr/share/doc/mibrfcs. Excluding those docs makes the package unusable.

Adding `echo 'path-include /usr/share/doc/mib*' > /etc/dpkg/dpkg.cfg.d/zz_include-mibs` to the Dockerfile solves it.

I suggest to add some small README, that documents what's excluded and how to change that.

**Comment by sathieu** [comment]
Also, empty man dirs are needed to install openjdk-7-jre or other pakages using update-alternatives their.

See https://github.com/nantesmetropole/docker-debian/commit/d405976525bb66c50c1f18d857438b86adf39d14 for the patch we use on our own images.

**Comment by hmalphettes** [comment]
@sathieu A postgres installation also expects `/usr/share/man/man{1..8}`.

I don't think those folders should be added to the slim image:
we must keep the `/usr/share/man` folder empty to keep the image smaller.
It is easier to be aware that a package fills it and that cleanup is needed.

Here is what I am using:
```
RUN bash -c 'mkdir -p /usr/share/man/man{1,2,3,4,5,6,7,8}' && \
  apt-get install postgres && \
  rm -rf /usr/share/man/*
```

**Comment by sathieu** [comment]
Does empty dirs make it actually bigger?

**Comment by hmalphettes** [comment]
@sathieu empty dirs don't make it bigger.
But it is harder to know that you should empty those directories to keep your image small:

Say I am building a `postgres:slim` image based on `debian:slim`.
After I install postgres, I should empty `/usr/share/man/`.
The fact that I had to create those folders to support the postgres install will naturally remind me that after the install, I should clean up the folder.

**Comment by colinmollenhour** [comment]
What about making "-slim" the default at some point and "-docs" the optional? Perhaps this would break too many images but it is unfortunate that so many other packages are built with so much unnecessary stuff bloating the images. For example, if I want a slim PHP image but don't want to use Alpine I have to use a version that includes all of these docs..

**Comment by tianon** [comment]
This repository is now deprecated in favor of https://github.com/debuerreotype/docker-debian-artifacts, which builds reproducible Debian rootfs tarballs using https://github.com/debuerreotype/debuerreotype. :+1:

This suggestion is implemented and working pretty well so far!  The most recent push removed both the "ping" and "ip" tools from the `slim` variant as well, with a savings of ~2MB. :+1:

**Comment by colinmollenhour** [comment]
@tianon I'm not sure removing "ip" is worthwhile.. I shouldn't assume my needs are typical, but it does seem like I end up using "ip route" and "ip addr" a lot in entrypoint scripts, especially since "ifconfig" is not available.

**Comment by tianon** [comment]
It's not "removing" `ip` so much as not specifically installing it.  When we use `--variant=minbase`, the `ip` utility is not included.

**Comment by tianon** [comment]
(It's easy for users to install, but impossible to remove and reclaim that space.)
