### ISSUE TITLE
sid/stretch minbase no longer includes /usr/bin/gpg

### ISSUE THREAD

**Issue by tianon** [tianon/docker-brew-debian#49]
Due to a change in APT (such that it no longer `Depends: gnupg` given that `gnupg` is only required for the optional `apt-key` functionality, and is thus now relegated to a `Recommends` relationship which `deboostrap` will not install), `gnupg` is no longer included in our sid/stretch images.  Reading through [`#830696`](https://bugs.debian.org/830696), this is firmly by-design (since otherwise, building a chroot without `gpg` would be a challenge).

Given that using `gpg` to verify downloaded artifacts in `Dockerfile`s is a very common practice (as is the use of `apt-key`), I'm opening this issue both to record my notes of why the change has occurred, and so that we (@paultag and I) can decide whether our "solution" here is to add `gnupg` to `--include` or whether for stretch and beyond, users should be told to explicitly install `gnupg` if they need signature verification (or even `apt-key`).

**Comment by tianon** [comment]
cc @yarikoptic, since I think this intersects with your interests too (and because the way we noticed the change was that `neurodebian`'s sid version failed to build given that it uses `apt-key` immediately :+1:)

**Comment by yarikoptic** [comment]
heh heh... thanks for the buzz @tianon !  so, doesn't it mean that now I would need to 

```Dockerfile
RUN apt-get update; apt-get install gnupg
... OLD RUNS adding the apt lines and running apt-key
RUN apt-get clean;  rm -f /var/lib/apt/lists/*   # to bring it back to clean state
```
probably right away starting with stretch ...  right?

or, alternatively, gnupg could indeed be just installed in the stock docker images for debian/ubuntu.  May be without any recommends:
```shell
root@6b2de87fd4a5:/var/lib/apt/lists# apt-get install gnupg --no-install-recommends
Reading package lists... Done
Building dependency tree... Done
The following additional packages will be installed:
  libreadline6 libusb-0.1-4 readline-common
Suggested packages:
  gnupg-doc libpcsclite1 parcimonie xloadimage | imagemagick | eog readline-doc
Recommended packages:
  gnupg-curl libldap-2.4-2
The following NEW packages will be installed:
  gnupg libreadline6 libusb-0.1-4 readline-common
0 upgraded, 4 newly installed, 0 to remove and 3 not upgraded.
Need to get 1388 kB of archives.
After this operation, 5749 kB of additional disk space will be used.
```
so probably would consume only about up to 5MB of space and seems to be sufficient to run apt-key command we use

**Comment by yarikoptic** [comment]
btw, for signature verification (alone) there is `gpgv` package/binary , which is available in the base.

**Comment by tianon** [comment]
@yarikoptic right, but without `gpg`, we can't use `--recv-keys` to get the key material to verify against :disappointed:

**Comment by tianon** [comment]
This repository is now deprecated in favor of https://github.com/debuerreotype/docker-debian-artifacts, which builds reproducible Debian rootfs tarballs using https://github.com/debuerreotype/debuerreotype. :+1:

I don't think we have a great solution here other than having all images which require it install `gnupg2` (and `dirmngr`) directly. :confused:

**Comment by tianon** [comment]
See https://github.com/docker-library/gcc/commit/00013aa569bfe01e32300b8eb70db417a43a7bb5 for a simple `RUN` line we've used successfully to install the necessary `gpg` bits when they're missing that works with a `FROM` that's either `jessie` or `stretch` interchangeably.

If Ubuntu is necessary as well, see https://github.com/neurodebian/dockerfiles/blob/54048bbf21fff2bce39ef6e040ab2312ddad05ab/dockerfiles/stretch/Dockerfile#L3-L18 for a more complex/complete version (since some versions of Ubuntu include GnuPG 2.x out-of-the-box, but not `dirmngr`, which is required for using `--recv-keys`).
