### ISSUE TITLE
systemctl gives error -1

### ISSUE THREAD

**Issue by kerbachi** [tianon/docker-brew-debian#52]
Impossible to use systemctl command with this image, it gives this error:

```
root@278f492e0747:/# systemctl daemon-reload
Failed to get D-Bus connection: Unknown error -1
root@278f492e0747:/# systemctl -a
Failed to get D-Bus connection: Unknown error -1
```

I have these packages installed though:

```
root@278f492e0747:/# dpkg -l | grep -i dbus
ii  dbus                                1.8.20-0+deb8u1              amd64        simple interprocess messaging system (daemon and utilities)
ii  libdbus-1-3:amd64                   1.8.20-0+deb8u1              amd64        simple interprocess messaging system (library)
ii  libdbus-glib-1-2:amd64              0.102-1                      amd64        simple interprocess messaging system (GLib-based shared library)
ii  libdbus2.0-cil                      0.8.1-1                      all          CLI implementation of D-Bus
```

**Comment by tianon** [comment]
This is the correct behavior -- `systemctl` is merely a client for talking to `systemd` directly via D-Bus, neither of which are normally running in a Docker container.

**Comment by kiemlicz** [comment]
But Debian Jessie is expected to be running _systemd_ by default.
According to your statement _debian:jessie_ is not jessie then?
How to workaround this (if using _debian:jessie_)?

**Comment by tianon** [comment]
@kiemlicz a normal install of Debian Jessie would run `systemd` as PID 1, yes, but in Docker, we do not run the init system of the container OS -- part of the main benefits of Docker is that your container doesn't _have_ to run all that, and can simply run the single application you need (NGINX, MySQL, etc)

So yes, this is a faithful Debian Jessie userspace environment, even if it's not running `systemd` (and for the record, using `sysvinit` as PID 1 on an normal system is also still supported by the Debian project)

**Comment by tianon** [comment]
This repository is now deprecated in favor of https://github.com/debuerreotype/docker-debian-artifacts, which builds reproducible Debian rootfs tarballs using https://github.com/debuerreotype/debuerreotype. :+1:
