### ISSUE TITLE
orkhan

### ISSUE THREAD

**Issue by Orxan1997** [tianon/docker-brew-debian#53]
Hello. help me
http://httpredir.debian.org/debian/dists/stable//Release.gpg

**Comment by Orxan1997** [comment]
please

**Comment by tianon** [comment]
You're definitely going to need to elaborate.  What's the issue you're seeing?

**Comment by tianon** [comment]
This repository is now deprecated in favor of https://github.com/debuerreotype/docker-debian-artifacts, which builds reproducible Debian rootfs tarballs using https://github.com/debuerreotype/debuerreotype. :+1:
