### ISSUE TITLE
Has the image been updated with the patches to fix the Dirty Cow vulnerability?

### ISSUE THREAD

**Issue by toby-griffiths** [tianon/docker-brew-debian#54]
Just been reading up on this & patching all my images that extend this one, but wanted to as whether this image has been updated to fix this yet?

**Comment by tianon** [comment]
The way Docker works, the images themselves don't contain the kernel, so as long as you update the kernel on your Docker host, you're good! :+1:

**Comment by toby-griffiths** [comment]
@tianon OK.  Thanks for advising :o)
