### ISSUE TITLE
wheezy bash segfault

### ISSUE THREAD

**Issue by ederrm** [tianon/docker-brew-debian#55]
```
erm@uhet ~> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
debian              wheezy-slim         dbb999842f63        10 days ago         47.67 MB
debian              wheezy              337681dc4ec4        10 days ago         84.91 MB
erm@uhet ~> docker run -it --rm debian:wheezy /bin/bash
erm@uhet ~> docker run -it --rm debian:wheezy /bin/sh
# bash    
Segmentation fault (core dumped)
# apt-get update
E: Method http has died unexpectedly!
E: Sub-process http received a segmentation fault.
E: Method http has died unexpectedly!
E: Sub-process http received a segmentation fault.
```

```
erm@uhet ~> docker --version
Docker version 1.12.3, build 6b644ec
```

```
erm@uhet ~> uname -a
Linux uhet 4.8.0-1-amd64 #1 SMP Debian 4.8.5-1 (2016-10-28) x86_64 GNU/Linux
```

**Comment by tianon** [comment]
Is your system low on memory?

**Comment by ederrm** [comment]
nop, I have 16GB here, and just 4gb is used right now,
I will downgrade my host kernel and try again

2016-11-18 17:37 GMT-02:00 Tianon Gravi <notifications@github.com>:

**Comment by ederrm** [comment]
With older host kernel works fine

```
erm@uhet ~> uname -a
Linux uhet 4.7.0-1-amd64 #1 SMP Debian 4.7.8-1 (2016-10-19) x86_64 GNU/Linux
erm@uhet ~> docker run -it --rm debian:wheezy /bin/bash
```

**Comment by yosifkit** [comment]
I just tested this on kernel `4.8.8` and I don't get any segfaults. :cry:

**Comment by tianon** [comment]
I can confirm on a Debian 4.8 kernel (`4.8.0-1-amd64 #1 SMP Debian 4.8.5-1` to be more exact), so I wonder if something changed in the Debian 4.8 kernel series configuration. :disappointed:

Do the same binaries in a normal wheezy `chroot` outside Docker exhibit the same issue, or is Docker itself introducing odd behavior here?

**Comment by ijc25** [comment]
@ederrm please see https://github.com/docker/docker/issues/28705#issuecomment-262226229

**Comment by ederrm** [comment]
@ijc25 thanks a lot, this: https://github.com/docker/docker/issues/28705#issuecomment-262268578
works fine for me
