### ISSUE TITLE
Include GnuPG

### ISSUE THREAD

**Issue by Daniel15** [tianon/docker-brew-debian#60]
Trying to add a Debian repo's GPG key via `apt-get` results in this message:
```
gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
```

Seeing as this is a very common thing to do, could you please include GnuPG in the Docker image?

**Comment by yosifkit** [comment]
This only effects stretch/sid and was reported in https://github.com/tianon/docker-brew-debian/issues/49.

From the Debian [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=830696):
> Apt recommends gnupg | gnupg2 which is the correct choice so we can build minimal environments
without pulling in the whole GPG stack (agent, other daemons).

This allows us to build smaller images and then let users install, use, and remove gpupg to keep their images slim too.

**Comment by Daniel15** [comment]
Thanks for the info! Closing this as a duplicate of #49.
