### ISSUE TITLE
 Failed to fetch https://download.docker.com/linux/ubuntu/dists/jessie/stable/binary-amd64/Packages 

### ISSUE THREAD

**Issue by fadyberty** [tianon/docker-brew-debian#62]
Get:56 https://apt.dockerproject.org ubuntu-jessie/main amd64 Packages [454 B]
Err https://apt.dockerproject.org ubuntu-jessie/main amd64 Packages
  HttpError403
Get:57 https://apt.dockerproject.org ubuntu-jessie/main Translation-en_US [454 B]
Ign https://apt.dockerproject.org ubuntu-jessie/main Translation-en_US    
Get:58 https://apt.dockerproject.org ubuntu-jessie/main Translation-en [454 B]
Ign https://apt.dockerproject.org ubuntu-jessie/main Translation-en    
Get:59 https://apt.dockerproject.org jessie/main amd64 Packages [454 B]
Err https://apt.dockerproject.org jessie/main amd64 Packages     
  HttpError403
Get:60 https://apt.dockerproject.org jessie/main Translation-en_US [454 B]
Ign https://apt.dockerproject.org jessie/main Translation-en_US           
Get:61 https://apt.dockerproject.org jessie/main Translation-en [454 B]   
Ign https://apt.dockerproject.org jessie/main Translation-en           
Get:62 https://download.docker.com jessie/stable Translation-en_US [587 B]
Get:63 https://download.docker.com jessie/stable Translation-en [584 B]   
Get:64 https://download.docker.com jessie/stable amd64 Packages [586 B]   
Get:65 http://deb.debian.org jessie/main amd64 Packages [6,776 kB]     
Get:66 https://download.docker.com jessie/stable Translation-en_US [587 B]
Get:67 https://download.docker.com jessie/stable Translation-en [584 B]                        
Get:68 https://download.docker.com jessie/stable amd64 Packages [586 B]                        
Get:69 http://deb.debian.org jessie/main Translation-en [4,582 kB]                          
Get:70 https://download.docker.com jessie/stable Translation-en_US [587 B]                
Get:71 https://download.docker.com jessie/stable Translation-en [584 B]                              
Get:72 https://download.docker.com jessie/stable amd64 Packages [586 B]                
Err https://download.docker.com jessie/stable amd64 Packages                           
  HttpError404
Get:73 https://download.docker.com jessie/stable Translation-en_US [587 B]       
Ign https://download.docker.com jessie/stable Translation-en_US                           
Get:74 https://download.docker.com jessie/stable Translation-en [584 B]                   
Ign https://download.docker.com jessie/stable Translation-en                           
Fetched 18.5 MB in 5s (3,627 kB/s)                                                     
W: Failed to fetch http://apt.dockerproject.org/repo/dists/ubuntu-jessie/main/binary-amd64/Packages  403  Forbidden

W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-jessie/main/binary-amd64/Packages  HttpError403

W: Failed to fetch https://apt.dockerproject.org/repo/dists/jessie/main/binary-amd64/Packages  HttpError403

W: Failed to fetch https://download.docker.com/linux/ubuntu/dists/jessie/stable/binary-amd64/Packages  HttpError404

E: Some index files failed to download. They have been ignored, or old ones used instead.
root@instance-1:/etc/apt/sources.list.d# less /etc/apt/sources.list
root@instance-1:/etc/apt/sources.list.d# apt-get install docker-ce
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package docker-ce

**Comment by tianon** [comment]
I think you've got the wrong repo -- this repository is for the `debian` official image, not for the Docker Project APT repos.  I'd recommend trying either https://github.com/docker/docker, or the Docker Community Slack (https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/). :+1:
