### ISSUE TITLE
More regular build?

### ISSUE THREAD

**Issue by pierreozoux** [tianon/docker-brew-debian#63]
As I said here:
https://github.com/gliderlabs/docker-alpine/issues/270

The last debian push was a month ago.
Should we rely on this image being up to date?
Or should we use `dist-upgrade` in our docker images?
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#run

Thanks for your comments :)

**Comment by tianon** [comment]
Usually we update every few weeks or when a major vuln/package update hits -- we've had a bit of lag due to other loads, but I'll go ahead and do an update now.  Thanks!
