### ISSUE TITLE
not able to extract the maven in debian (version 16.06)

### ISSUE THREAD

**Issue by tweaty100** [tianon/docker-brew-debian#67]
hello @tianon 
root@cf8b1803ada8:/# tar -xJf node-v4.4.3-linux-x64.tar.xz 
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
please help as i am new to linux and  i am not getting what to do. 
thanks

**Comment by tianon** [comment]
See https://github.com/tianon/docker-brew-debian/issues/40#issuecomment-312458854.

**Comment by tweaty100** [comment]
hello @tianon sir
i am not able to understand from there.please explain

Thanks

**Comment by tianon** [comment]
Run something like `apt-get update && apt-get install -y xz-utils` and that will install `xz`, which will allow your `tar` command to complete.

**Comment by tweaty100** [comment]
hello @tianon 
i got this error 
![maven1](https://user-images.githubusercontent.com/26880613/27803811-10f79db8-6049-11e7-8bce-c32e5953ca12.jpg)
