### ISSUE TITLE
not able to start npm for dragonboard 

### ISSUE THREAD

**Issue by tweaty100** [tianon/docker-brew-debian#68]
i am not able to setup Amazon Alexa Voice Control Service on the Dragonboard 410c. is someone facing same problem please help as when i typed command npm start it throws so many errors
![1 2](https://user-images.githubusercontent.com/26880613/27802884-22a2f04e-6044-11e7-9f1e-2ede39cbea37.jpeg)
![1 3](https://user-images.githubusercontent.com/26880613/27802898-4480c13c-6044-11e7-851c-9eba02907c96.jpeg)

**Comment by tianon** [comment]
I think you've got the wrong repository -- this is the (old) location for reporting issues about the Docker Official Image of Debian, not Debian itself (nor `npm`). :sweat_smile:

**Comment by tweaty100** [comment]
hello @tianon 
i am new to linux can you please explain it so i am not getting sir
Thanks

**Comment by tweaty100** [comment]
i am getting this error how to resolve this error please help
![npm1](https://user-images.githubusercontent.com/26880613/27803671-529a243a-6048-11e7-8391-fa1bde60e28d.jpg)
![npm2](https://user-images.githubusercontent.com/26880613/27803696-73af1356-6048-11e7-89c3-788124f7d18c.jpg)
![npm3](https://user-images.githubusercontent.com/26880613/27803786-f87ab28e-6048-11e7-8c84-a869a81de38d.jpg)
